---
title: "Use of Bank and Credit Cards"
author: 
  - Çetiner, Çağla[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->

[^1]: 19080388 , [Github Repo](https://github.com/caglacetiner/proposal.git)



# Introduction

Recently, the use of debit and credit cards has become quite common in Turkey. The number of bank and credit card usage is increasing and the places used are also changing due to this situation. Now instead of cash, cards are used in every areas. People are starting to not carry money on them, which shows that people are used to debit and credit cards. Debit and credit cards are now used in many areas. Especially in internet shopping, the most important thing is the use of debit and credit cards. Recently, internet expenditures constitute a large part of Turkey's bank and credit card expenditures. The contributing factors will be explored. For this analysis, the data set obtained by the central bank of the Republic of Turkey is used. The data consists of 73 observers and 15 variables. By using the monthly values of the last 5 years, it will be investigated how the difference has changed in terms of variables (clothing, health, food, internet) and which factors have an effect on this.




## Literature Review

The beginning of the use of debit and credit cards does not date back to ancient times. The idea of card payment was first introduced in a science fiction novel in 1887. This novel is Edward Bellamy's book "Looking Backward Or Life In The Year 2000". At the end of the 18th century, the United States introduced a card that allowed the purchase of goods and services without paying cash. In Turkey, the first credit card use was with Diners Club in 1968 and very few people had this card in those years. [@kaya:2009; @bayrakdarouglu:2015] Since then, the use of bank and credit cards has continued to increase until today. There are many reasons for the increase in the use of debit and credit cards. First of all, according to the study of Evans (2008), the use of debit and credit cards has increased visibly in the last thirty years. Credit cards have helped households (low-income families) buy things they couldn't get with cash, and Credit card loans have led households to have trouble-free consumption throughout their lives. At the same time, it has been observed that it affects the use of debit and credit cards in developed and developing countries.[@Evans:2004] 

Kaynak and Küçükemiroğlu(1995) examined credit card usage behavior in developed and developing countries (Turkey) and stated that the increase in bank and credit card usage is related to socio-economic and technological developments, and that the use of credit cards increases especially in developing countries.[@Kaynak:1995]

Borzekowski and Kiser (2008) examined the payment preferences of consumers such as using debit cards, general purpose credit cards, petrol credit cards or cash and how it is determined. According to them, consumers who are less educated, low-income, middle-aged are found to have fewer credit cards and are more likely to use cash, and those who use debit and credit cards are younger and more educated.[@borzekowski:2008]

However, the consumer Payment Choice Diary was made by the Federal Reserve. They have sought to understand the payment habits of the US population. Kim, Kumar and O’Brien (2016) highlight their findings in October every year since 2016. According to them, as in the findings in 2018, cash accounted for 35 percent of face-to-face payments, and debit cards have been the most preferred payment system in recent years. The results of the 2020 Diary said that many consumers prefer to use cash for daily payments, while others continue to emphasize that they use cash as a backup payment tool even when opting for debit and credit cards. One of the reasons for the increase in the use of credit cards is clearly indicated by the work of platinum in the army province. [@kim:2020]

In the survey conducted by Pilatin (2021) with 425 people on the factors affecting the use of credit cards in Turkey, it was understood that the most important factor in the use of credit cards in the province of Ordu is that credit cards provide the opportunity to shop in installments.[@Pilatin:2021]

One of the other reasons, Ağan (2020), is related to the change of the payment system with covid-19. In the 2019-2020 period, the use of bank and credit cards has increased due to the effects of covid-19 in the world. Especially the 'contactless' feature that came to cards played an important role during the pandemic period. Fear of the virus transmitted by cash, people have moved away from paying cash and started using debit and credit cards. 
In addition, the use of debit and credit cards has been affected by cultural factors.[@Ağan:2020]

Gul (2014),found significant relationships between the use of bank and credit cards and the increase in tourism demand. With the recent globalization, the tourism sector has had a great importance in the world. And this has led to an increase in tourism in Turkey. The increase in tourism demand is related to the purchasing power and it has been tried to determine the relationship between the spending that comes with the increase in purchasing power and the use of credit cards. Today, the developing card payment system has increased the spending in Turkish tourism. It has been shown that tourists can travel as they wish without the need to convert their money and carry cash. One of the reasons why tourists use credit cards is that they can shop in installments and at the same time, they spend less money with the same income level.[@Gul:2014]










\newpage
# References {#references}
<div id="refs"></div>

